import {pick} from 'lodash';
import {
  DeserializeOptions,
  SArray,
  SObject,
  SStringNT,
  SUInt16BE,
  SUInt8,
  SerializeOptions,
  field,
} from 'serio';

/** Maximum number of categories.
 *
 * References:
 *   - https://github.com/jichu4n/palm-os-sdk/blob/master/sdk-3.1/include/Core/System/DataMgr.h#L34
 */
export const NUM_CATEGORIES = 16;
/** Maximum length of category labels - 15 chars + 1 NUL byte.
 *
 * References:
 *   - https://github.com/jichu4n/palm-os-sdk/blob/master/sdk-3.1/include/Core/System/DataMgr.h#L35
 */
export const CATEGORY_LABEL_LENGTH = 16;

/** Information about a category.
 *
 * The member fields inside a Category object aren't actually stored together as
 * a single unit; instead, they are split across the `categoryLabels`,
 * `categoryUniqIds` and `renamedCategories` fields inside {@link AppInfoType}.
 * However, we still make Category extend `SObject` in order to present a
 * consistent API for interacting with database objects.
 */
export class Category extends SObject {
  /** Name of the category.
   *
   * Max length is CATEGORY_LABEL_LENGTH - 1.
   */
  label = '';
  /** ID of the category.
   *
   * Unique IDs generated by the device are between 0 and 127. Unique IDs
   * generated by the desktop computer are between 128 and 255.
   */
  uniqId = 0;
  /** Dirty bit indicating whether this category has been renamed. */
  isRenamed = false;

  toJSON() {
    return pick(this, ['label', 'uniqId', 'isRenamed']);
  }
}

/** AppInfo block for standard category data.
 *
 * References:
 *   - https://jichu4n.github.io/palm-pdb/assets/Palm%20File%20Format%20Specification.pdf
 *   - https://github.com/jichu4n/palm-os-sdk/blob/master/sdk-5r3/include/Core/UI/Category.h
 */
export class AppInfoType extends SObject {
  /** Array of category information (dmRecNumCategories = 16 elements). */
  categories: Array<Category> = [];
  @field(SUInt16BE)
  private renamedCategories = 0;
  @field(
    SArray.of(SStringNT.ofLength(CATEGORY_LABEL_LENGTH)).ofLength(
      NUM_CATEGORIES
    )
  )
  private categoryLabels: Array<string> = [];
  @field(SArray.of(SUInt8).ofLength(NUM_CATEGORIES))
  private categoryUniqIds: Array<number> = [];

  /** The last unique category ID assigned. */
  @field(SUInt8)
  lastUniqId = 0;

  @field(SUInt8)
  private readonly padding1 = 0;

  /** Finds the category with the given unique ID or label.
   *
   * If the argument is a number, this method will look for a category with a
   * matching uniqId. If the argument is a string, this method will look for a
   * category with a matching label.
   */
  getCategory(arg: number | string): Category | null {
    let matchFn: (category: Category) => boolean;
    switch (typeof arg) {
      case 'number':
        matchFn = (category) => category.uniqId === arg;
        break;
      case 'string':
        matchFn = (category) => category.label === arg;
        break;
      default:
        throw new Error(`Expected a number or string, found ${typeof arg}`);
    }
    return this.categories.find(matchFn) ?? null;
  }

  deserialize(buffer: Buffer, opts?: DeserializeOptions) {
    const offset = super.deserialize(buffer, opts);
    this.categories = [];
    for (let i = 0; i < NUM_CATEGORIES; ++i) {
      if (!this.categoryLabels[i]) {
        break;
      }
      this.categories.push(
        Category.with({
          label: this.categoryLabels[i],
          uniqId: this.categoryUniqIds[i],
          isRenamed: !!(this.renamedCategories & (1 << i)),
        })
      );
    }
    return offset;
  }

  serialize(opts?: SerializeOptions): Buffer {
    this.categoryLabels = [];
    this.categoryUniqIds = [];
    this.renamedCategories = 0;
    for (let i = 0; i < this.categories.length; ++i) {
      const {label, uniqId, isRenamed} = this.categories[i];
      this.categoryLabels.push(label);
      this.categoryUniqIds.push(uniqId);
      if (isRenamed) {
        this.renamedCategories |= 1 << i;
      }
    }
    return super.serialize(opts);
  }
}
